export const countries = [
  "Afeganistão",
  "Albânia",
  "Argélia",
  "Andorra",
  "Angola",
  "Argentina",
  "Armênia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Bielorrússia",
  "Bélgica",
  "Belize",
  "Benin",
  "Butão",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botswana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Camboja",
  "Camarões",
  "Canadá",
  "Chade",
  "Chile",
  "China",
  "Colômbia",
  "Comores",
  "Congo",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Chipre",
  "República Tcheca",
  "Dinamarca",
  "Djibuti",
  "Dominica",
  "República Dominicana",
  "Equador",
  "Egito",
  "El Salvador",
  "Guiné Equatorial",
  "Eritreia",
  "Estônia",
  "Essuatíni",
  "Etiópia",
  "Fiji",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Geórgia",
  "Alemanha",
  "Gana",
  "Grécia",
  "Granada",
  "Guatemala",
  "Guiné",
  "Guiné-Bissau",
  "Guiana",
  "Haiti",
  "Honduras",
  "Hungria",
  "Islândia",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Cazaquistão",
  "Quênia",
  "Kiribati",
  "Coreia do Norte",
  "Coreia do Sul",
  "Kosovo",
  "Kuwait",
  "Quirguistão",
  "Laos",
  "Letônia",
  "Líbano",
  "Lesoto",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Madagascar",
  "Malawi",
  "Malásia",
  "Maldivas",
  "Mali",
  "Malta",
  "Ilhas Marshall",
  "Mauritânia",
  "Maurício",
  "México",
  "Micronésia",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Marrocos",
  "Moçambique",
  "Mianmar (Birmânia)",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Países Baixos",
  "Nova Zelândia",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Macedônia do Norte",
  "Noruega",
  "Omã",
  "Paquistão",
  "Palau",
  "Palestina",
  "Panamá",
  "Papua-Nova Guiné",
  "Paraguai",
  "Peru",
  "Filipinas",
  "Polônia",
  "Portugal",
  "Catar",
  "Romênia",
  "Rússia",
  "Ruanda",
  "São Cristóvão e Nevis",
  "Santa Lúcia",
  "São Vicente e Granadinas",
  "Samoa",
  "San Marino",
  "São Tomé e Príncipe",
  "Arábia Saudita",
  "Senegal",
  "Sérvia",
  "Seychelles",
  "Serra Leoa",
  "Cingapura",
  "Eslováquia",
  "Eslovênia",
  "Ilhas Salomão",
  "Somália",
  "África do Sul",
  "Espanha",
  "Sri Lanka",
  "Sudão",
  "Suriname",
  "Suécia",
  "Suíça",
  "Síria",
  "Taiwan",
  "Tajiquistão",
  "Tanzânia",
  "Tailândia",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunísia",
  "Turquia",
  "Turcomenistão",
  "Tuvalu",
  "Uganda",
  "Ucrânia",
  "Emirados Árabes Unidos",
  "Reino Unido",
  "Estados Unidos",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnã",
  "Iêmen",
  "Zâmbia",
  "Zimbábue",
];

export const STEPS = [
  { label: "Dados Pessoais", step: 0 },
  { label: "Endereço e Contatos", step: 1 },
  { label: "Passaporte", step: 2 },
  { label: "Sobre a Viagem", step: 3 },
  { label: "Acompanhante da Viagem", step: 4 },
  { label: "Viagens Anteriores", step: 5 },
  { label: "Contato nos Estados Unidos", step: 6 },
  { label: "Informações Familiares", step: 7 },
  { label: "Trabalho e Educação", step: 8 },
  { label: "Informações Adicionais", step: 9 },
  { label: "Segurança", step: 10 },
] as const;

export const USALocations = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
