export type AcompanhamentoRecord = {
  id: string;
  userId: string | null;
  profileId: string | null;
  formStep: number;
  name: string;
  barcode: string;
  barcodeIssued: string;
  barcodeExpire: string;
  barcodeDone: boolean;
  casv: string;
  interview: string;
  meeting: string;
  shipping: string;
  tipo: string;
  resp: string;
  tax: string;
  ds160: string;
  alimto: string;
  obs: string;
  dob: string;
  passport: string;
  account: string;
  email: string;
  phone: string;
  entryDate: string;
  group: string;
  pagto: string;
  status: string;
};
